apiVersion: v2
name: nublado2
version: 0.5.8
appVersion: "1.4.3"
description: Nublado2 JupyterHub installation
home: https://github.com/lsst-sqre/nublado2
maintainers:
  - name: cbanek
sources:
  - https://github.com/lsst-sqre/nublado2
  - https://github.com/lsst-sqre/charts
kubeVersion: ">=1.16.0-0"
dependencies:
  - name: jupyterhub
    version: "1.1.4"
    repository: https://jupyterhub.github.io/helm-chart/
