apiVersion: v2
name: nublado2
version: 0.8.3
appVersion: "2.0.1"
description: Nublado2 JupyterHub installation
home: https://github.com/lsst-sqre/nublado2
maintainers:
  - name: cbanek
sources:
  - https://github.com/lsst-sqre/nublado2
  - https://github.com/lsst-sqre/charts
kubeVersion: ">=1.16.0-0"
dependencies:
  - name: jupyterhub
    version: "1.1.3-n324.hb93a9b5f"  # Change when JH 2.1.1 chart is official
    repository: https://jupyterhub.github.io/helm-chart/
