# Default values for nublado2.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

jupyterhub:
  hub:
    image:
      name: lsstsqre/nublado2
      tag: "1.0.1"
    containerSecurityContext:
      runAsUser: 768
      runAsGroup: 768
      allowPrivilegeEscalation: false
    baseUrl: '/n2'
    # Note: this has to match up with the kubernetes secret created by the vault secret,
    # and since you can't put templating in a values file, I'm just setting the name here,
    # as well as in vault_secret_name, which should match.
    existingSecret: "nublado2-secret"
    extraConfig:
      nublado.py: |
        import nublado2.hub_config
        nublado2.hub_config.HubConfig().configure(c)
    extraVolumes:
      - name: nublado-config
        configMap:
          name: nublado-config
    extraVolumeMounts:
      - name: nublado-config
        mountPath: /etc/jupyterhub/nublado_config.yaml
        subPath: nublado_config.yaml
    networkPolicy:
      # This is set to disabled but is basically re-implemented by
      # the netpol.yaml in this chart.
      enabled: false

  prePuller:
    continuous:
      enabled: false
    hook:
      enabled: false

  singleuser:
    cmd: "/opt/lsst/software/jupyterlab/provisionator.bash"
    defaultUrl: "/lab"

  auth:
    type: custom
    custom:
      className: nublado2.auth.GafaelfawrAuthenticator
    state:
      enabled: true

  # This is specific to the outdated 0.9.0-n409.hce116620 version of the
  # chart.  When we upgrade to the current version, change this setting
  # to:
  #
  # proxy:
  #   chp:
  #     networkPolicy:
  #       interNamespaceAccessLabels: accept
  proxy:
    service:
      type: ClusterIP
    networkPolicy:
      ingress:
        - ports:
            - port: http
          from:
            - podSelector:
                matchLabels:
                  hub.jupyter.org/network-access-proxy-http: "true"
              namespaceSelector:
                matchLabels: {}

  # Any instantiation of this chart must also set ingress.hosts and add
  # the nginx.ingress.kubernetes.io/auth-signin annotation pointing to the
  # appropriate fully-qualified URLs for the Gafaelfawr /login route.
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/auth-method: GET
      nginx.ingress.kubernetes.io/auth-response-headers: "X-Auth-Request-Token"
      nginx.ingress.kubernetes.io/auth-url: "http://gafaelfawr-service.gafaelfawr.svc.cluster.local:8080/auth?scope=exec:notebook"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        error_page 403 = "/auth/forbidden?scope=exec:notebook";

config:
  # base_url must be set in each instantiation of this chart to the URL of
  # the primary ingress.  It's used to construct API requests to the
  # authentication service (which should go through the ingress).
  base_url: ""

  # What uid should the pod be started as?  If it is set, use that uid for
  # starting each pod.  If not set, use the uid provided from gafaelfawr in
  # auth.
  # Sometimes, we start the pod as the provisioning user (uid 769) which has
  # the permission to sudo to do the work of changing to the user.
  pod_uid: 769
  options_form:
    images: []
    images_url: "http://cachemachine.cachemachine/cachemachine/jupyter/available"
    sizes:
      - name: Tiny
        cpu: .5
        ram: 1536M
      - name: Small
        cpu: 1
        ram: 3072M
      - name: Medium
        cpu: 2
        ram: 6144M
      - name: Large
        cpu: 4
        ram: 12288M
  user_resources: {}

# Note: See note above about existingSecret.
vault_secret_name: "nublado2-secret"
vault_secret_path: ""

# Pull secret:
pull_secret: ""

network_policy:
  enabled: true
