# Default values for nublado2.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

jupyterhub:
  hub:
    containerSecurityContext:
      runAsUser: 768
      runAsGroup: 768
      fsGroup: 768
      allowPrivilegeEscalation: false
    baseUrl: '/n2'
    extraConfig:
      nublado.py: |
        import nublado2.hub_config
        nublado2.hub_config.HubConfig().configure(c)
    extraVolumes:
      - name: nublado-config
        configMap:
          name: nublado-config
    extraVolumeMounts:
      - name: nublado-config
        mountPath: /etc/jupyterhub/nublado_config.yaml
        subPath: nublado_config.yaml

  auth:
    type: custom
    custom:
      className: nublado2.auth.GafaelfawrAuthenticator

config: {}
