# -- Version of the Strimzi Custom Resource API. The correct value depends on
# the deployed version of Strimzi. See [this blog
# post](https://strimzi.io/blog/2021/04/29/api-conversion/) for more.
strimziAPIVersion: v1beta2

cluster:
  # -- Name used for the Kafka broker, and used by Strimzi for many annotations.
  name: alert-broker

kafka:
  # -- Version of Kafka to deploy.
  version: 2.8.1
  # -- Encoding version for messages, see
  # https://strimzi.io/docs/operators/latest/deploying.html#ref-kafka-versions-str.
  logMessageFormatVersion: 2.8
  # -- Version of the protocol for inter-broker communication, see
  # https://strimzi.io/docs/operators/latest/deploying.html#ref-kafka-versions-str.
  interBrokerProtocolVersion: 2.8

  # -- Number of Kafka broker replicas to run.
  replicas: 3

  storage:
    # -- Size of the backing storage disk for each of the Kafka brokers.
    size: 1000Gi
    # -- Name of a StorageClass to use when requesting persistent volumes.
    storageClassName: standard

  # -- Configuration overrides for the Kafka server.
  config:
    # -- Number of minutes for a consumer group's offsets to be retained.
    offsets.retention.minutes: 10080
    # -- Number of days for a topic's data to be retained.
    log.retention.hours: 168
    # -- Maximum retained number of bytes for a topic's data. This is a string
    # -- to avoid YAML type conversion issues for large numbers.
    log.retention.bytes: "644245094400"

  externalListener:
    bootstrap:
      # -- IP address that should be used by the broker's external bootstrap load
      # balancer for access from the internet. The format of this is a string like
      # "192.168.1.1".
      ip: ""
      # -- Hostname that should be used by clients who want to connect to the
      # broker through the bootstrap address.
      host: ""

    # -- List of hostname and IP for each broker. The format of this is a list
    # of maps with 'ip' and 'host' keys. For example:
    #
    #    - ip: "192.168.1.1"
    #      host: broker-0.example
    #    - ip: "192.168.1.2"
    #      host: broker-1.example
    #
    # Each replica should get a host and IP. If these are unset, then IP
    # addresses will be chosen automatically by the Kubernetes cluster's
    # LoadBalancer controller, and hostnames will be unset, which will break
    # TLS connections.
    brokers: []

# -- A list of usernames for users who should have global admin permissions.
# These users will be created, along with their credentials.
superusers:
  - kafka-admin

zookeeper:
  # -- Number of Zookeeper replicas to run.
  replicas: 3

  storage:
    # -- Size of the backing storage disk for each of the Zookeeper instances.
    size: 1000Gi
    # -- Name of a StorageClass to use when requesting persistent volumes.
    storageClassName: standard

tls:
  subject:
    # -- Organization to use in the 'Subject' field of the broker's TLS certifcates.
    organization: "Vera C. Rubin Observatory"
