# Default values for cadc-tap.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Number of pods to start
replicaCount: 1

# -- Override the base name for resources
nameOverride: ""

# -- Override the full name for resources (includes the release name)
fullnameOverride: ""

image:
  # -- tap image to use
  repository: "lsstdax/lsst-tap-service"

  # -- Pull policy for the tap image
  pullPolicy: "IfNotPresent"

  # -- Tag of tap image to use
  # @default -- The appVersion of the chart
  tag: ""

# -- Secret names to use for all Docker pulls
imagePullSecrets: []

service:
  # -- Type of service to create
  type: ClusterIP

  # -- Port of the service to create and map to the ingress
  port: 80

# Settings for the ingress rules.
ingress:
  # -- Hostname for the ingress
  # @default -- None, must be set
  host: ""

  # -- Gafaelfawr auth query string
  gafaelfawrAuthQuery: "scope=read:tap&auth_type=basic&delegate_to=tap"

  # -- Additional annotations to use for endpoints that allow anonymous
  # access, such as `/capabilities` and `/availability`
  anonymousAnnotations: {}

  # -- Additional annotations to use for endpoints that are authenticated,
  # such as `/sync`, `/async`, and `/tables`
  authenticatedAnnotations: {}

networkPolicy:
  # -- Whether to restrict access to the service. Only enable if the ingress
  # controller namespace is tagged with `gafaelfawr.lsst.io/ingress: "true"`.
  enabled: false

# -- Resource limits and requests for the Gafaelfawr frontend pod
resources: {}

# -- Annotations for the Gafaelfawr frontend pod
podAnnotations: {}

# -- Node selector rules for the Gafaelfawr frontend pod
nodeSelector: {}

# -- Tolerations for the Gafaelfawr frontend pod
tolerations: []

# -- Affinity rules for the Gafaelfawr frontend pod
affinity: {}

# -- Path to the Vault secret (`secret/k8s_operator/<host>/tap`, for example)
# @default -- None, must be set
vaultSecretsPath: ""

config:
  # -- Address to a MySQL database containing TAP schema data
  tapSchemaAddress: "tap-schema-db.tap-schema.svc.cluster.local:3306"

  # -- Datalink payload URL
  datalinkPayloadUrl: "https://github.com/lsst/sdm_schemas/releases/download/1.1.4/datalink-snippets.zip"

  # -- Gafaelfawr hostname to get user information from a token
  # @default -- Value of `ingress.host`
  gafaelfawrHost: ""

  # -- Name of GCS bucket in which to store results
  # @default -- None, must be set
  gcsBucket: ""

  # -- Base URL for results stored in GCS bucket
  # @default -- None, must be set
  gcsBucketUrl: ""

  # -- Java heap size, which will set the maximum size of the heap. Otherwise
  # Java would determine it based on how much memory is available and black
  # maths.
  jvmMaxHeapSize: 4G

qserv:
  # -- QServ hostname:port to connect to
  # @default -- `"mock-qserv:3306"` (the mock QServ)
  host: "mock-qserv:3306"

  mock:
    # -- Spin up a container to pretend to be QServ.
    enabled: true

    image:
      # -- Mock QServ image to use
      repository: "lsstdax/mock-qserv"

      # -- Pull policy for the mock QServ image
      pullPolicy: "IfNotPresent"

      # -- Tag of mock QServ image to use
      # @default -- The appVersion of the chart
      tag: ""

    # -- Resource limits and requests for the mock QServ pod
    resources: {}

    # -- Annotations for the mock QServ pod
    podAnnotations: {}

    # -- Node selection rules for the mock QServ pod
    nodeSelector: {}

    # -- Tolerations for the mock QServ pod
    tolerations: []

    # -- Affinity rules for the mock QServ pod
    affinity: {}

uws:
  image:
    # -- UWS database image to use
    repository: "lsstdax/uws-db"

    # -- Pull policy for the UWS database image
    pullPolicy: "IfNotPresent"

    # -- Tag of UWS database image to use
    # @default -- The appVersion of the chart
    tag: ""

  # -- Resource limits and requests for the UWS database pod
  resources: {}

  # -- Annotations for the UWS databse pod
  podAnnotations: {}

  # -- Node selection rules for the UWS database pod
  nodeSelector: {}

  # -- Tolerations for the UWS database pod
  tolerations: []

  # -- Affinity rules for the UWS database pod
  affinity: {}
