# Default values for cadc-tap.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

imagePullPolicy: "Always"

# pull secret name
pull_secret: ""

# Version tag of all images to use.
tag: "1.0.22"

# QServ hostname:port to connect to.
# If you're using mock_qserv, this value should be fine.
qserv_host: "qserv-master01:4040"

# Address to a mysql database containing TAP schema data.
tap_schema_address: "tap-schema-db.tap-schema.svc.cluster.local:3306"

# Spin up a container to pretend to be QServ.
use_mock_qserv: true

gcs_bucket: ""
gcs_bucket_url: ""

vault_secrets:
  # Use the vault-secrets-operator to load secrets from vault
  # instead of creating them from values here.
  enabled: false

  # Path to load secrets for in the vault.
  path: ""

secrets:
  # Create a normal k8s secret using the values provided here.
  # Even if you don't have these secrets, you still need to have
  # either secrets.enabled or vault_secrets.enabled.
  enabled: true

  # GCE service account credential JSON file, base64 encoded.
  # You can also pass this in using --set-file secrets.google_creds=google_creds.json
  # on the command line, to allow not checking it in.
  google_creds: ""

  # Slack webhook URL, base64 encoded.
  # This is the URL that the querymonkey should use to post issues about
  # running queries on.  Since this is a secret, unauthenticated randomly
  # generated URL, you can pass it in using either
  # --set-file secrets.slack_webhook_url=webhook_file or
  # --set-string secrets.slack_webhook_url=https://slack.com/url .
  slack_webhook_url: ""

# Number of querymonkey instances.  0 by default (which is off).
# This is because the querymonkey doesn't work with the mock_qserv
# (due to the lack of scisql function support).
querymonkey_replicas: 0

# Settings for the ingress rules.
ingress:
  # Force SSL, which is used in annotations and rewriting redirects.
  ssl: true
  # Additional annotations to use for endpoints that allow anonymous
  # access, such as /capabilities, /availability
  anonymous_annotations: {}
  # Additional annotations to use for endpoints that are authenticated,
  # such as /sync, /async, /tables
  authenticated_annotations: {}

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

# Setting for the java heap size, which will set the maximum size of the heap.  Otherwise
# java will determine it based on how much memory is available and black maths.
jvm_max_heap_size: 4G

aux_resources: {}
  # Same for resources, but for the non-main TAP service services (such as databases).

nodeSelector: {}

tolerations: []

affinity: {}
