kind: Service
apiVersion: v1
metadata:
  name: {{ template "cadc-tap.fullname" . }}
  labels:
    {{- include "cadc-tap.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: "TCP"
      port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    {{- include "cadc-tap.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: "server"
