apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ template "cadc-tap.fullname" . }}-secret
  labels:
    {{- include "cadc-tap.labels" . | nindent 4 }}
spec:
  path: {{ required "vaultSecretsPath must be set" .Values.vaultSecretsPath | quote }}
  type: Opaque
