apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "semaphore.fullname" . }}
  labels:
    {{- include "semaphore.labels" . | nindent 4 }}
data:
  SAFIR_NAME: {{ .Values.config.name | quote }}
  SAFIR_PROFILE: {{ .Values.config.profile | quote }}
  SAFIR_LOG_LEVEL: {{ .Values.config.log_level | quote }}
  SAFIR_LOGGER: {{ .Values.config.logger_name | quote }}
