{{- if .Values.tokens.secrets -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "gafaelfawr.fullname" . }}-tokens
  labels:
    {{- include "gafaelfawr.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.config.kubernetes.schedule | quote }}
  jobTemplate:
    spec:
      template:
        metadata:
          {{- with .Values.tokens.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          labels:
            {{- include "gafaelfawr.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/component: "tokens"
        spec:
          restartPolicy: "Never"
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "gafaelfawr.tokensServiceAccountName" . }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
          containers:
            - name: "gafaelfawr"
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - "all"
                readOnlyRootFilesystem: true
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
              args:
                - "gafaelfawr"
                - "update-service-tokens"
              env:
                - name: "GAFAELFAWR_DATABASE_PASSWORD"
                  valueFrom:
                    secretKeyRef:
                      name: {{ template "gafaelfawr.fullname" . }}-secret
                      key: "database-password"
              {{- with .Values.resources }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
              {{- end }}
              volumeMounts:
                - name: "config"
                  mountPath: "/etc/gafaelfawr"
                  readOnly: true
                - name: "secret"
                  mountPath: "/etc/gafaelfawr/secrets"
                  readOnly: true
            {{- if .Values.cloudsql.enabled }}
            - name: "cloud-sql-proxy"
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - "all"
                readOnlyRootFilesystem: true
              image: "{{ .Values.cloudsql.image.repository }}:{{ .Values.cloudsql.image.tag }}"
              imagePullPolicy: {{ .Values.cloudsql.image.pullPolicy | quote }}
              command:
                - "/cloud_sql_proxy"
                - "-ip_address_type=PRIVATE"
                - "-instances={{ required "cloudsql.instanceConnectionName must be specified" .Values.cloudsql.instanceConnectionName }}=tcp:5432"
              securityContext:
                runAsNonRoot: true
                runAsUser: 65532
                runAsGroup: 65532
            {{- end }}
          volumes:
            - name: "config"
              configMap:
                name: {{ template "gafaelfawr.fullname" . }}-config
            - name: "secret"
              secret:
                secretName: {{ template "gafaelfawr.fullname" . }}-secret
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
