apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: {{ template "helpers.fullname" . }}-ingress
spec:
  rules:
{{ if .Values.ingress.host }}
  - host: {{ .Values.ingress.host }}
    http:
{{ else }}
  - http:
{{ end }}
      paths:
      - path: /auth
        backend:
          serviceName: {{ template "helpers.fullname" . }}-service
          servicePort: 8080
      - path: /login
        backend:
          serviceName: {{ template "helpers.fullname" . }}-service
          servicePort: 8080
      - path: /logout
        backend:
          serviceName: {{ template "helpers.fullname" . }}-service
          servicePort: 8080
      - path: /oauth2/callback
        backend:
          serviceName: {{ template "helpers.fullname" . }}-service
          servicePort: 8080
      - path: /.well-known/jwks.json
        backend:
          serviceName: {{ template "helpers.fullname" . }}-service
          servicePort: 8080
      {{- if .Values.oidc_server.enabled }}
      - path: /.well-known/openid-configuration
        backend:
          serviceName: {{ template "helpers.fullname" . }}-service
          servicePort: 8080
      {{- end }}
