{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: "/auth/tokens/"
    nginx.ingress.kubernetes.io/use-regex: "true"
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ template "gafaelfawr.fullname" . }}-rewrite
  labels:
    {{- include "gafaelfawr.labels" . | nindent 4 }}
spec:
  rules:
    {{- if .Values.ingress.host }}
    - host: {{ .Values.ingress.host }}
      http:
    {{- else }}
    - http:
    {{- end }}
        {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
        paths:
          - path: "/auth/tokens/id/.*"
            pathType: Prefix
            backend:
              service:
                name: {{ template "gafaelfawr.fullname" . }}
                port:
                  number: 8080
        {{- else }}
        paths:
          - path: "/auth/tokens/id/.*"
            backend:
              serviceName: {{ template "gafaelfawr.fullname" . }}
              servicePort: 8080
        {{- end }}
