apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ template "gafaelfawr.fullname" . }}
  labels:
    {{- include "gafaelfawr.labels" . | nindent 4 }}
spec:
  rules:
    {{- if .Values.ingress.host }}
    - host: {{ .Values.ingress.host }}
      http:
    {{- else }}
    - http:
    {{- end }}
        paths:
          - path: "/auth"
            backend:
              serviceName: {{ template "gafaelfawr.fullname" . }}
              servicePort: 8080
          - path: "/login"
            backend:
              serviceName: {{ template "gafaelfawr.fullname" . }}
              servicePort: 8080
          - path: "/logout"
            backend:
              serviceName: {{ template "gafaelfawr.fullname" . }}
              servicePort: 8080
          - path: "/oauth2/callback"
            backend:
              serviceName: {{ template "gafaelfawr.fullname" . }}
              servicePort: 8080
          - path: "/.well-known/jwks.json"
            backend:
              serviceName: {{ template "gafaelfawr.fullname" . }}
              servicePort: 8080
          {{- if .Values.config.oidcServer.enabled }}
          - path: "/.well-known/openid-configuration"
            backend:
              serviceName: {{ template "gafaelfawr.fullname" . }}
              servicePort: 8080
          {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
