apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-request-redirect: $request_uri
    nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-Token
    nginx.ingress.kubernetes.io/auth-signin: https://{{ .Values.host }}/login
    nginx.ingress.kubernetes.io/auth-url: http://gafaelfawr-service.{{ .Release.Namespace }}:8080/auth?scope={{ .Values.user_scope }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      error_page 403 = "/auth/forbidden?scope={{ .Values.user_scope }}";
  name: {{ template "helpers.fullname" . }}-token-ingress
spec:
  rules:
{{ if .Values.ingress.host }}
  - host: {{ .Values.ingress.host }}
    http:
{{ else }}
  - http:
{{ end }}
      paths:
      - path: /auth/token
        backend:
          serviceName: {{ template "helpers.fullname" . }}-service
          servicePort: 8080
