{{- /*
  Revert c8641fd03f71762b252bab10aacd932acfb5298a when Argo CD has been
  fixed to pass in cluster capabilities, or when all clusters are running
  Kubernetes 1.19 or later.
*/ -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: "/auth/tokens/"
    nginx.ingress.kubernetes.io/use-regex: "true"
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ template "gafaelfawr.fullname" . }}-rewrite
  labels:
    {{- include "gafaelfawr.labels" . | nindent 4 }}
spec:
  rules:
    {{- if .Values.ingress.host }}
    - host: {{ .Values.ingress.host }}
      http:
    {{- else }}
    - http:
    {{- end }}
        paths:
          - path: "/auth/tokens/id/.*"
            backend:
              serviceName: {{ template "gafaelfawr.fullname" . }}
              servicePort: 8080
