{{- if .Values.tokens.secrets -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "gafaelfawr.fullname" . }}-post-install
  labels:
    {{- include "gafaelfawr.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: "post-install,post-upgrade"
    helm.sh/hook-weight: "-1"
    helm.sh/hook-delete-policy: "before-hook-creation,hook-succeeded"
spec:
  template:
    metadata:
      name: {{ template "gafaelfawr.fullname" . }}-postinstall-init
      labels:
        {{- include "gafaelfawr.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: "postinstall"
    spec:
      restartPolicy: OnFailure
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gafaelfawr.tokensServiceAccountName" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        {{- if .Values.cloudsql.enabled }}
        - name: "cloud-sql-proxy"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "all"
            readOnlyRootFilesystem: true
            runAsUser: 65532
            runAsGroup: 65532
          image: "{{ .Values.cloudsql.image.repository }}:{{ .Values.cloudsql.image.tag }}"
          imagePullPolicy: {{ .Values.cloudsql.image.pullPolicy | quote }}
          command: ["/bin/sh", "-c"]
          args:
            - |
                set -e
                /cloud_sql_proxy -ip_address_types=PRIVATE -instances={{ required "cloudsql.instanceConnectionName must be specified" .Values.cloudsql.instanceConnectionName }}=tcp:5432 &
                PID=$!
                while true; do
                    if [ -f "/lifecycle/main-terminated" ]; then
                        kill $PID
                        exit 0
                    fi
                    sleep 1
                done
          volumeMounts:
            - name: "lifecycle"
              mountPath: "/lifecycle"
        {{- end }}
        - name: "gafaelfawr"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "all"
            readOnlyRootFilesystem: true
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command: ["/bin/sh", "-c"]
          args:
            - |
                set -e
                gafaelfawr init
                gafaelfawr update-service-tokens
                touch /lifecycle/main-terminated
          env:
            - name: "GAFAELFAWR_DATABASE_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: {{ template "gafaelfawr.fullname" . }}-secret
                  key: "database-password"
          {{- with .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 16 }}
          {{- end }}
          volumeMounts:
            - name: "config"
              mountPath: "/etc/gafaelfawr"
              readOnly: true
            - name: "secret"
              mountPath: "/etc/gafaelfawr/secrets"
              readOnly: true
            - name: "lifecycle"
              mountPath: "/lifecycle"
      volumes:
        - name: "config"
          configMap:
            name: {{ template "gafaelfawr.fullname" . }}-config
        - name: "secret"
          secret:
            secretName: {{ template "gafaelfawr.fullname" . }}-secret
        - name: "lifecycle"
          emptyDir: {}
{{- end }}
