apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "gafaelfawr.fullname" . }}-redis
  labels:
    {{- include "gafaelfawr.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "gafaelfawr.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "redis"
  template:
    metadata:
      labels:
        {{- include "gafaelfawr.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: "redis"
    spec:
      automountServiceAccountToken: false
      containers:
        - name: "redis"
          image: "redis"
          imagePullPolicy: "Always"
          args:
            - "redis-server"
            - "--appendonly"
            - "yes"
            - "--requirepass"
            - "$(REDIS_PASSWORD)"
          env:
            - name: "REDIS_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: {{ template "gafaelfawr.fullname" . }}-secret
                  key: "redis-password"
          livenessProbe:
            exec:
              command:
                - "sh"
                - "-c"
                - "redis-cli -h $(hostname) incr health:counter"
            initialDelaySeconds: 15
            periodSeconds: 30
          ports:
            - containerPort: 6379
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "100m"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "all"
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: "redis-data"
              mountPath: "/data"
      {{- if .Values.pull_secret }}
      imagePullSecrets:
        - name: {{ .Values.pull_secret }}
      {{- end }}
      securityContext:
        fsGroup: 999
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
      volumes:
        - name: redis-data
          {{- if .Values.redis_claim }}
          persistentVolumeClaim:
            claimName: {{ .Values.redis_claim }}
          {{- else }}
          emptyDir: {}
          {{- end }}
