apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "gafaelfawr.fullname" . }}-redis-networkpolicy
  labels:
    {{- include "gafaelfawr.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "gafaelfawr.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "redis"
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "gafaelfawr.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: "frontend"
      ports:
        - protocol: "TCP"
          port: 6379
