{{- if .Values.config.kubernetes.serviceSecrets -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gafaelfawr.fullname" . }}-secrets
  labels:
    {{- include "gafaelfawr.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ required "cloudsql.serviceAccount must be set to a valid Google service account" .Values.cloudsql.serviceAccount | quote }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "gafaelfawr.fullname" . }}-secrets
  labels:
    {{- include "gafaelfawr.labels" . | nindent 4 }}
rules:
  apiGroups: [""]
  resources: ["secret"]
  verbs: ["delete", "get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "gafaelfawr.fullname" . }}-secrets
  labels:
    {{- include "gafaelfawr.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "gafaelfawr.fullname" . }}-secrets
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "gafaelfawr.fullname" . }}-secrets
  apiGroup: rbac.authorization.k8s.io/v1
{{- end }}
