{{- if and .Values.tokens.serviceAccount.create .Values.tokens.secrets -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gafaelfawr.tokensServiceAccountName" . }}
  labels:
    {{- include "gafaelfawr.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.cloudsql.enabled }}
    iam.gke.io/gcp-service-account: {{ required "cloudsql.serviceAccount must be set to a valid Google service account" .Values.cloudsql.serviceAccount | quote }}
    {{- end }}
    {{- with .Values.tokens.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "gafaelfawr.fullname" . }}-tokens
  labels:
    {{- include "gafaelfawr.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["delete", "get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "gafaelfawr.fullname" . }}-tokens
  labels:
    {{- include "gafaelfawr.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "gafaelfawr.tokensServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "gafaelfawr.fullname" . }}-tokens
  apiGroup: rbac.authorization.k8s.io
{{- end }}
