{{ if .Values.ingress.enabled }}
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: {{ template "mobu.fullname" . }}
  labels:
    app: {{ template "mobu.fullname" . }}
    chart: {{ template "mobu.chart" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
{{ if .Values.ingress.annotations }}
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{ end }}
spec:
  rules:
{{ if .Values.host }}
  - host: {{ .Values.host }}
    http:
{{ else }}
  - http:
{{ end }}
      paths:
      - backend:
          serviceName: {{ template "mobu.fullname" . }}
          servicePort: 8080
        path: /mobu
{{ end }}
