{{- if .Values.publish_url }}
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ include "sherlock.fullname" . }}-secret
  labels:
    {{- include "sherlock.labels" . | nindent 4 }}
spec:
  path: {{ required "vaultSecretsPath must be set" .Values.vaultSecretsPath | quote }}
  type: Opaque
{{- end }}
