# Hostname used to construct issuers and URLs.
# e.g. lsst-lsp-<instance>.ncsa.illinois.edu
host: ""

# Controls the host for the ingress.  Normally set to the same value as
# the realm, but leave blank for environments using the wildcard virtual
# host (such as nublado.lsst.codes).
ingress:
  host: ""

# Session length/Token expiration (in minutes)
session_length: 1440

# Existing PVC for redis claim
# If empty, redis will use emptydir
redis_claim: ""

vault_secrets:
  # secret/k8s_operator/<host>/gafaelfawr
  path: ""

# <client id from cilogon.org or OIDC provider>
oauth2_proxy_client_id: "" 

# Default capability required for user-based operations (like generating a token)
user_capability: "exec:user"

# Docker image to use.
image: "lsstdm/jwt_authorizer:0.3.0"

config:
  loglevel: DEBUG

  # Defining all capabilites applications may need.
  # This feeds into the token downlad page
  known_capabilities:
    "exec:portal": Use the Portal to execute operations. Mostly used from notebook APIs.
    "read:image": Read images from the SODA and other image retrieval interfaces
    "read:image/metadata": Read image metadata from SIA and other image interfaces
    "read:tap": Execute SELECT queries in the TAP interface on project datasets
    "read:tap/efd": Execute SELECT queries in the TAP interface on EFD datasets
    "read:tap/user": Execute SELECT queries in the TAP interface on your data
    "write:tap/user": Upload tables to your database workspace
    "read:tap/history": Read the history of your TAP queries.
    "read:workspace": Read project datasets from the file workspace
    "read:workspace/user": Read the data in your file workspace
    "write:workspace/user": Write data to your file workspace

  # Mapping of capabilities to groups that are part of the `isMemberOf` claim
  group_mapping:
    exec:admin: ["lsst_int_lsp_admin"]
    exec:user: ["lsst_int_lspdev"]
    read:workspace: ["lsst_int_lspdev"]
    read:workspace/user: ["lsst_int_lspdev"]
    write:workspace/user: ["lsst_int_lspdev"]
    exec:portal: ["lsst_int_lspdev"]
    exec:notebook: ["lsst_int_lspdev"]
    read:tap: ["lsst_int_lspdev"]
    read:image: ["lsst_int_lspdev"]
