apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ include "cert-issuer.fullname" . }}
  labels:
    {{- include "cert-issuer.labels" . | nindent 4 }}
spec:
  path: {{ required "config.vaultSecretPath must be set" .Values.config.vaultSecretPath | quote }}
  type: Opaque
