# Default values for landing-page.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

ingress:
  # -- Additional annotations to add to the ingress
  annotations: {}

  # -- Configures TLS for the ingress if needed. If multiple ingresses share
  # the same hostname, only one of them needs a TLS configuration.
  tls: []

# This is a link to a markdown file containing the message of the day.
# Point this at a URL containing messages you want to show to the users.
motd_url: https://raw.githubusercontent.com/lsst-dm/lsp-landing-page/master/motd/Readme.md

image:
  repository: lsstsqre/lsp-landing-page
  tag: latest

pull_secret: ""

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
