# Default values for <CHARTNAME>.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Number of web deployment pods to start
replicaCount: 1

image:
  # -- Image to use in the <CHARTNAME> deployment
  repository: lsstsqre/<CHARTNAME>

  # -- Pull policy for the <CHARTNAME> image
  pullPolicy: Always

  # -- Overrides the image tag whose default is the chart appVersion.
  tag: ""

# -- Secret names to use for all Docker pulls
imagePullSecrets: []

# -- Override the base name for resources
nameOverride: ""

# -- Override the full name for resources (includes the release name)
fullnameOverride: ""

# -- Annotations for the <CHARTNAME> deployment pod
podAnnotations: {}

service:
  # -- Type of service to create
  type: ClusterIP

  # -- Port of the service to create and map to the ingress
  port: 8080

ingress:
  # -- Create an ingress resource
  enabled: true

  # -- Hostname of the deployment to run behind
  host: ""

  # -- Gafaelfawr Auth Query string (default, unauthenticated)
  #gafaelfawrAuthQuery: "scope=exec:portal&delegate_to=portal&delegate_scope=read:tap"
  gafaelfawrAuthQuery: ""

  # -- Additional annotations for the ingress rule
  annotations: {}

  # -- Path type for the ingress rule
  pathType: ImplementationSpecific

  # -- URL path to dispatch to the <CHARTNAME> deployment pod
  path: "/api/<CHARTNAME>"

# -- Resource limits and requests for the <CHARTNAME> deployment pod
resources: {}

autoscaling:
  # -- Enable autoscaling of <CHARTNAME> deployment
  enabled: false

  # -- Minimum number of <CHARTNAME> deployment pods
  minReplicas: 1

  # -- Maximum number of <CHARTNAME> deployment pods
  maxReplicas: 100

  # -- Target CPU utilization of <CHARTNAME> deployment pods
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# -- Node selection rules for the <CHARTNAME> deployment pod
nodeSelector: {}

# -- Tolerations for the <CHARTNAME> deployment pod
tolerations: []

# -- Affinity rules for the <CHARTNAME> deployment pod
affinity: {}
