apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ template "neophile.fullname" . }}-secret
  labels:
    {{- include "neophile.labels" . | nindent 4 }}
spec:
  path: {{ .Values.vaultSecretsPath }}
  type: Opaque
