apiVersion: v1
kind: Service
metadata:
  name: {{ include "mobu.fullname" . }}
  labels:
    {{- include "mobu.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: "http"
      protocol: "TCP"
  selector:
    {{- include "mobu.selectorLabels" . | nindent 4 }}
