{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "mobu.serviceAccountName" . }}
  labels:
{{ include "mobu.labels" . | indent 4 }}
{{- if .Values.pull_secret }}
imagePullSecrets:
- name: {{ .Values.pull_secret }}
{{- end }}
{{- end -}}
