{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "mobu.serviceAccountName" . }}
  labels:
{{ include "mobu.labels" . | indent 4 }}
{{- end -}}
