hostname: ""
# Include leading forward slash in basePath
basePath: "/plot-navigator"
image:
  repository: lsstdm/pipetask-plot-navigator
  tag: ""

# Environment variables to be passed to panel.
# e.g. butler configuration and auth params.
environment: {}

# Path to the vault secret.
butler_secret_path: ""

ingress:
  annotations: {}
