apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: postgres
  labels:
    app: {{ template "postgres.fullname" . }}
{{ include "postgres.labels" . | indent 4 }}
spec:
  path: '{{ .Values.vault_secrets.path }}'
  type: Opaque
