# Default values for times-square.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Number of web deployment pods to start
replicaCount: 1

image:
  # -- Image to use in the times-square deployment
  repository: lsstsqre/timessquare

  # -- Pull policy for the times-square image
  pullPolicy: Always

  # -- Overrides the image tag whose default is the chart appVersion.
  tag: ""

# -- Secret names to use for all Docker pulls
imagePullSecrets: []

# -- Override the base name for resources
nameOverride: ""

# -- Override the full name for resources (includes the release name)
fullnameOverride: ""

# -- Annotations for the times-square deployment pod
podAnnotations: {}

service:
  # -- Type of service to create
  type: ClusterIP

  # -- Port of the service to create and map to the ingress
  port: 8080

ingress:
  # -- Create an ingress resource
  enabled: true

  # -- Hostname of the deployment to run behind
  host: ""

  # -- Gafaelfawr auth query string (default, unauthenticated)
  gafaelfawrAuthQuery: ""

  # -- Additional annotations for the ingress rule
  annotations: {}

  # -- Path type for the ingress rule
  pathType: ImplementationSpecific

  # -- URL path to dispatch to the times-square deployment pod
  path: "/api/times-square"

# -- Resource limits and requests for the times-square deployment pod
resources: {}

autoscaling:
  # -- Enable autoscaling of times-square deployment
  enabled: false

  # -- Minimum number of times-square deployment pods
  minReplicas: 1

  # -- Maximum number of times-square deployment pods
  maxReplicas: 100

  # -- Target CPU utilization of times-square deployment pods
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# -- Node selection rules for the times-square deployment pod
nodeSelector: {}

# -- Tolerations for the times-square deployment pod
tolerations: []

# -- Affinity rules for the times-square deployment pod
affinity: {}

# -- Path to the Vault secret (`secret/k8s_operator/<host>/times-square`, for
# example)
# @default -- None, must be set
vaultSecretsPath: ""

# Configurations for the times-square application.
config:
  # -- Name of the service.
  name: "times-square"

  # -- Run profile: "production" or "development"
  profile: "production"

  # -- Logging level: "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"
  logLevel: "INFO"

  # -- Logger name
  loggerName: "times-square"

  # -- RSP hostname, for computing internal service URLs
  # @default -- None, must be set
  environmentUrl: ""

redis:
  auth:
    enabled: false
