apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: strimzischemaregistries.roundtable.lsst.codes
spec:
  scope: Namespaced
  group: roundtable.lsst.codes
  versions:
    - name: v1beta1
      served: true
      storage: true
  names:
    kind: StrimziSchemaRegistry
    plural: strimzischemaregistries
    singular: strimzischemaregistry
    shortNames:
      - ssrs
      - ssr
