apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: strimzischemaregistries.roundtable.lsst.codes
spec:
  scope: Namespaced
  group: roundtable.lsst.codes
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: >-
            StrimziSchemaRegistry represents a desired Schema Registry instance
          type: object

  names:
    kind: StrimziSchemaRegistry
    plural: strimzischemaregistries
    singular: strimzischemaregistry
    shortNames:
      - ssrs
      - ssr
