apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "firefly.fullname" . }}
  labels:
{{ include "firefly.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "firefly.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "firefly.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: firefly
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /firefly/shared-workarea
          name: firefly-shared-workarea
        - mountPath: /firefly/config
          name: firefly-config
          readOnly: true
        env:
        - name: MANAGER
          value: "TRUE"
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "firefly.fullname" . }}-secret
              key: ADMIN_PASSWORD
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "firefly.fullname" . }}-secret
              key: ADMIN_PASSWORD
        - name: FIREFLY_OPTS
          value: "-Dvisualize.fits.search.path=/datasets -Dredis.host={{ include "firefly.fullname" . }}-redis"
        - name: SERVER_CONFIG_DIR
          value: /firefly/config
        - name: MAX_JVM_SIZE
          value: "{{ .Values.max_jvm_size }}"
        - name: DEBUG
          value: "{{ .Values.debug }}"
      {{- if .Values.pull_secret }}
      imagePullSecrets:
      - name: {{ .Values.pull_secret }}
      {{- end }}
      volumes:
      - name: datasets
        {{- if .Values.volumes.datasets_hostpath }}
        hostPath:
          path: {{ .Values.volumes.datasets_hostpath }}
          type: Directory
        {{- else if.Values.volumes.datasets_nfs }}
        nfs:
          path: {{ .Values.volumes.datasets_nfs.path }}
          server: {{ .Values.volumes.datasets_nfs.server }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: firefly-shared-workarea
        {{- if .Values.volumes.firefly_shared_workarea_hostpath }}
        hostPath:
          path: {{ .Values.volumes.firefly_shared_workarea_hostpath }}
          type: Directory
        {{- else if.Values.volumes.firefly_shared_workarea_nfs }}
        nfs:
          path: {{ .Values.volumes.firefly_shared_workarea_nfs.path }}
          server: {{ .Values.volumes.firefly_shared_workarea_nfs.server }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: firefly-config
        {{- if .Values.volumes.firefly_config_hostpath }}
        hostPath:
          path: {{ .Values.volumes.firefly_config_hostpath }}
          type: Directory
        {{- else if.Values.volumes.firefly_config_nfs }}
        nfs:
          path: {{ .Values.volumes.firefly_config_nfs.path}}
          server: {{ .Values.volumes.firefly_config_nfs.server}}
        {{- else }}
        emptyDir: {}
        {{- end }}
