apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "cadc-tap-postgres.fullname" . }}-uws-db
  labels:
    app: {{ template "cadc-tap-postgres.fullname" . }}-uws-db
{{ include "cadc-tap-postgres.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "cadc-tap-postgres.fullname" . }}-uws-db
  template:
    metadata:
      labels:
        app: {{ template "cadc-tap-postgres.fullname" . }}-uws-db
{{ include "cadc-tap-postgres.labels" . | indent 8 }}
    spec:
      containers:
      - name: postgresql
        image: lsstdax/tap-postgres-uws:{{ .Values.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - containerPort: 5432
        resources:
          {{toYaml .Values.aux_resources | nindent 10}}
      {{- if .Values.pull_secret }}
      imagePullSecrets:
      - name: {{ .Values.pull_secret }}
      {{- end }}
