apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ template "cadc-tap-postgres.fullname" . }}
  labels:
    {{- include "cadc-tap-postgres.labels" . | nindent 4 }}
spec:
  path: {{ .Values.vaultSecretsPath }}
  type: Opaque
