apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "moneypenny.fullname" . }}-m-config
  labels:
{{ include "moneypenny.labels" . | indent 4 }}
data:
  m.yaml:
{{- toYaml .Values.orders | indent 2 }}
