apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "moneypenny.fullname" . }}-quips
  labels:
{{ include "moneypenny.labels" . | indent 4 }}
data:
  quips.txt:
{{- toYaml .Values.quips | indent 2 }}
