kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "moneypenny.serviceAccountName" . }}
  labels:
    {{- include "moneypenny.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: [ "pods" ]
    verbs: ["get", "create",  "delete"]  
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create",  "delete"]
