apiVersion: v1
kind: Service
metadata:
  name: {{ include "moneypenny.fullname" . }}
  labels:
    {{- include "moneypenny.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | quote }}
  ports:
    - name: "http"
      protocol: "TCP"
      port: {{ .Values.service.port }}
      targetPort: "http"
  selector:
    {{- include "moneypenny.selectorLabels" . | nindent 4 }}
