apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "moneypenny.serviceAccountName" . }}
  labels:
    {{- include "moneypenny.labels" . | nindent 4 }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
