apiVersion: v1
kind: Service
metadata:
  name: {{ include "moneypenny.fullname" . }}
  labels:
{{ include "moneypenny.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  selector:
    app.kubernetes.io/name: {{ include "moneypenny.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
