{{ if .Values.vault_secrets.enabled }}
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ .Values.vault_secrets.name }}
  labels:
    app: {{ template "moneypenny.fullname" . }}
{{ include "moneypenny.labels" . | indent 4 }}
spec:
  path: {{ .Values.vault_secrets.path }}
  type: kubernetes.io/dockerconfigjson
{{ end }}
