apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "helpers.fullname" . }}-configmap
data:
  authorizer.yaml: |
    default:
      realm: {{ .Values.host }}
      loglevel: {{ .Values.config.loglevel }}
      session_secret_file: /etc/gafaelfawr/secrets/session_secret.txt

      known_capabilities:
        {{- range $key, $value := .Values.config.known_capabilities }}
        {{ $key | quote }}: {{ $value | quote }}
        {{- end }}

      group_mapping:
        {{- range $key, $value := .Values.config.group_mapping }}
        {{ $key | quote }}: {{ $value }}
        {{- end }}

      {{- if .Values.config.github }}
      github:
        client_id: {{ .Values.config.github.client_id }}
        client_secret_file: /etc/gafaelfawr/secrets/github_client_secret.txt
      {{- end }}

      oauth2_store_session:
        ticket_prefix: "oauth2_proxy"
        redis_url: redis://{{ template "helpers.fullname" . }}-redis-service.{{ .Release.Namespace }}.svc.cluster.local:6379/0
        oauth2_proxy_secret_file: /etc/gafaelfawr/secrets/oauth2_proxy_cookie_secret.txt

      oauth2_jwt_exp: {{ .Values.session_length }}
      oauth2_jwt:
        iss: https://{{ .Values.host }}
        key_id: reissuer
        aud:
          default: https://{{ .Values.host }}
          internal: https://{{ .Values.host }}/api
        key_file: /etc/gafaelfawr/secrets/signing_key.pem

      issuers:
        https://{{ .Values.host }}:
          audience:
            - "https://{{ .Values.host }}"
            - "https://{{ .Values.host }}/api"
          issuer_key_ids: ["reissuer"]
