apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: {{ template "helpers.fullname" . }}-ingress
spec:
  rules:
{{ if .Values.ingress.host }}
  - host: {{ .Values.ingress.host }}
    http:
{{ else }}
  - http:
{{ end }}
      paths:
      - path: /auth
        pathType: Prefix
        backend:
          serviceName: {{ template "helpers.fullname" . }}
          servicePort: 8080
      - path: /login
        pathType: Exact
        backend:
          serviceName: {{ template "helpers.fullname" . }}
          servicePort: 8080
      - path: /.well-known/jwks.json
        pathType: Exact
        backend:
          serviceName: {{ template "helpers.fullname" . }}
          servicePort: 8080
