apiVersion: v1
kind: Service
metadata:
  name: {{ template "helpers.fullname" . }}-service
  labels:
    app: {{ template "helpers.fullname" . }}
spec:
  ports:
  - name: {{ template "helpers.fullname" . }}-http
    protocol: TCP
    port: 8080
    targetPort: app
  selector:
    name: {{ template "helpers.fullname" . }}
  sessionAffinity: None
  type: ClusterIP
