apiVersion: v1
kind: Service
metadata:
  name: {{ include "squash-api.fullname" . }}-redis
  labels:
{{ include "squash-api.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: "redis"
      port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "squash-api.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
