# Default values for neophile.

# -- Override the base name for resources
nameOverride: ""

# -- Override the full name for resources (includes the release name)
fullnameOverride: ""

image:
  # -- neophile image to use
  repository: "lsstsqre/neophile"

  # -- Pull policy for the neophile image
  pullPolicy: "IfNotPresent"

  # -- Tag of neophile image to use
  # @default -- The appVersion of the chart
  tag: ""

# -- Secret names to use for all Docker pulls
imagePullSecrets: []

persistence:
  # -- Name of an existing PVC to use for checkouts
  # @default -- Use an ephemeral `emptyDir`
  volumeClaim: ""

# -- Execution schedule as a cron string
# @default -- `0 4 * * 1` (4am on Monday)
schedule: "0 4 * * 1"

# -- Path to the Vault secret (`secret/k8s_operator/<host>/neophile`, for
# example)
# @default -- None, must be set
vaultSecretsPath: ""

# -- Resource limits and requests for the Gafaelfawr frontend pod
resources: {}

# -- Annotations for the Gafaelfawr frontend pod
podAnnotations: {}

# -- Node selector rules for the Gafaelfawr frontend pod
nodeSelector: {}

# -- Tolerations for the Gafaelfawr frontend pod
tolerations: []

# -- Affinity rules for the Gafaelfawr frontend pod
affinity: {}

config:
  # -- Name of the GitHub user (must match the token in the secret)
  # @default -- None, must be set
  githubUser: ""

  # -- Email address to use for GitHub commits
  # @default -- Public email address of the user
  githubEmail: ""

  # -- Repositories to monitor as a list of dicts with `owner` and `repo` keys
  repositories: []
