apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "vo-cutouts.fullname" . }}-config
  labels:
    {{- include "vo-cutouts.labels" . | nindent 4 }}
data:
  CUTOUT_BUTLER_REPOSITORY: {{ required "config.butlerRepository must be set" .Values.config.butlerRepository | quote }}
  CUTOUT_BUTLER_COLLECTION: {{ required "config.butlerCollection must be set" .Values.config.butlerCollection | quote }}
  CUTOUT_DATABASE_URL: {{ required "config.databaseUrl must be set" .Values.config.databaseUrl | quote }}
  CUTOUT_TIMEOUT: {{ .Values.config.timeout | quote }}
  CUTOUT_LIFETIME: {{ .Values.config.lifetime | quote }}
  CUTOUT_REDIS_HOST: "redis://{{ template "vo-cutouts.fullname" . }}-redis.{{ .Release.Namespace }}"
  CUTOUT_SYNC_TIMEOUT: {{ .Values.config.syncTimeout | quote }}
  SAFIR_LOG_LEVEL: {{ .Values.config.loglevel | quote }}
