apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "vo-cutouts.fullname" . }}
  labels:
    {{- include "vo-cutouts.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "vo-cutouts.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "frontend"
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "vo-cutouts.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: "frontend"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or .Values.serviceAccount.create .Values.cloudsql.enabled }}
      serviceAccountName: {{ include "vo-cutouts.serviceAccountName" . }}
      {{- else }}
      automountServiceAccountToken: false
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      initContainers:
        - name: "fix-secret-permissions"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command:
            - "/bin/bash"
            - "-c"
            - |
              # The Butler PostgreSQL secret must be owned by the appuser
              cp -RL /etc/vo-cutouts/secrets-raw/* /etc/vo-cutouts/secrets
              chown appuser:appuser /etc/vo-cutouts/secrets/*
              chmod 0400 /etc/vo-cutouts/secrets/*
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
            runAsGroup: 0
          volumeMounts:
            - name: "secrets"
              mountPath: "/etc/vo-cutouts/secrets"
            - name: "secrets-raw"
              mountPath: "/etc/vo-cutouts/secrets-raw"
              readOnly: true
      containers:
        {{- if .Values.cloudsql.enabled }}
        - name: "cloud-sql-proxy"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "all"
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65532
            runAsGroup: 65532
          image: "{{ .Values.cloudsql.image.repository }}:{{ .Values.cloudsql.image.tag }}"
          imagePullPolicy: {{ .Values.cloudsql.image.pullPolicy | quote }}
          command:
            - "/cloud_sql_proxy"
            - "-ip_address_types=PRIVATE"
            - "-instances={{ required "cloudsql.instanceConnectionName must be specified" .Values.cloudsql.instanceConnectionName }}=tcp:5432"
        {{- end }}
        - name: "vo-cutouts"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "all"
            readOnlyRootFilesystem: true
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          ports:
            - containerPort: 8080
              name: "http"
              protocol: "TCP"
          env:
            - name: "AWS_SHARED_CREDENTIALS_FILE"
              value: "/etc/vo-cutouts/secrets/aws-credentials"
            - name: "CUTOUT_DATABASE_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: {{ template "vo-cutouts.fullname" . }}-secret
                  key: "database-password"
            - name: "CUTOUT_REDIS_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: {{ template "vo-cutouts.fullname" . }}-secret
                  key: "redis-password"
            - name: "GOOGLE_APPLICATION_CREDENTIALS"
              value: "/etc/vo-cutouts/secrets/google-credentials"
            - name: "PGPASSFILE"
              value: "/etc/vo-cutouts/secrets/postgres-credentials"
            - name: "S3_ENDPOINT_URL"
              value: "https://storage.googleapis.com"
          envFrom:
            - configMapRef:
                name: {{ template "vo-cutouts.fullname" . }}-config
          readinessProbe:
            httpGet:
              path: "/cutout/availability"
              port: "http"
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: "secrets"
              mountPath: "/etc/vo-cutouts/secrets"
            - name: "tmp"
              mountPath: "/tmp"
      volumes:
        - name: "secrets"
          emptyDir: {}
        - name: "secrets-raw"
          secret:
            secretName: {{ template "vo-cutouts.fullname" . }}-secret
            defaultMode: 0400
        - name: "tmp"
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
