{{- /*
  Update apiVersion when Argo CD has been fixed to pass in cluster
  capabilities, or when all clusters are running Kubernetes 1.19 or later.
*/ -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: "/api/cutouts$1"
    nginx.ingress.kubernetes.io/use-regex: "true"
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ template "vo-cutouts.fullname" . }}
  labels:
    {{- include "vo-cutouts.labels" . | nindent 4 }}
spec:
  rules:
    - host: {{ required "ingress.host must be set" .Values.ingress.host | quote }}
      http:
        paths:
          - path: "/api/cutouts(.*)"
            backend:
              serviceName: {{ template "vo-cutouts.fullname" . }}
              servicePort: 8080
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
