apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ template "vo-cutouts.fullname" . }}-secret
  labels:
    {{- include "vo-cutouts.labels" . | nindent 4 }}
spec:
  path: {{ required "vaultSecretsPath must be set" .Values.vaultSecretsPath | quote }}
  type: Opaque
