apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "helpers.fullname" . }}
  labels:
    app: {{ template "helpers.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ template "helpers.fullname" . }}
  template:
    metadata:
      labels:
        name: {{ template "helpers.fullname" . }}
    spec:
      containers:
        - name: {{ template "helpers.fullname" . }}
          imagePullPolicy: "Always"
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
          - name: postgres
            containerPort: 5432
          volumeMounts:
            - name: storage
              mountPath: /var/lib/postgresql
          env:
          - name: DEBUG
            value: '{{ .Values.debug }}'
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "helpers.fullname" . }}
                key: root_password
          {{- with .Values.jupyterhub_db }}
          - name: VRO_DB_JUPYTERHUB_USER
            value: {{ .user }}
          - name: VRO_DB_JUPYTERHUB_DB
            value: {{ .db }}
          - name: VRO_DB_JUPYTERHUB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "helpers.fullname" . }}
                key: jupyterhub_password
          {{- end }}
            
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ template "helpers.fullname" . }}-physpvc
