apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "postgres.fullname" . }}
  labels:
    app: {{ template "postgres.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ template "postgres.fullname" . }}
  template:
    metadata:
      labels:
        name: {{ template "postgres.fullname" . }}
    spec:
      containers:
        - name: {{ template "postgres.fullname" . }}
          imagePullPolicy: "Always"
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
          - name: postgres
            containerPort: 5432
          volumeMounts:
            - name: storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ template "postgres.fullname" . }}-physpvc
