apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "postgres.fullname" . }}
  labels:
    app: {{ template "postgres.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ template "postgres.fullname" . }}
  template:
    metadata:
      labels:
        name: {{ template "postgres.fullname" . }}
    spec:
      containers:
        - name: {{ template "postgres.fullname" . }}
          imagePullPolicy: "Always"
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
          - name: postgres
            containerPort: 5432
          volumeMounts:
            - name: storage
              mountPath: /var/lib/postgresql/data
          env:
          {{- with .Values.jupyterhub_db }}
          - name: VRO_DB_JUPYTERHUB_USER
            value: {{ .user }}
          - name: VRO_DB_JUPYTERHUB_DB
            value: {{ .db }}
          {{- end }}
            
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ template "postgres.fullname" . }}-physpvc
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "postgres.fullname" . }}
              key: root_password
        {{- with .Values.jupyterhub_db }}
        - name: VRO_DB_JUPYTERHUB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "postgres.fullname" . }}
              key: jupyterhub_password
        {{- end }}
