kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "cachemachine.serviceAccountName" . }}-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: {{ template "cachemachine.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "cachemachine.serviceAccountName" . }}-cluster-role
  apiGroup: rbac.authorization.k8s.io
