kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "cachemachine.serviceAccountName" . }}-cluster-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]
