apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cachemachine.fullname" . }}-autostart
  labels:
{{ include "cachemachine.labels" . | indent 4 }}
data:
  {{- toYaml .Values.autostart | nindent 2 }}
