apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "cachemachine.fullname" . }}-pull-networkpolicy
spec:
  podSelector:
    matchLabels:
      cachemachine: pull
  policyTypes:
    - Ingress
    - Egress
