kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "cachemachine.serviceAccountName" . }}-role-binding
subjects:
  - kind: ServiceAccount
    name: {{ template "cachemachine.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "cachemachine.serviceAccountName" . }}-role
  apiGroup: rbac.authorization.k8s.io
