kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "cachemachine.serviceAccountName" . }}-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["create", "delete"]
- apiGroups: ["apps"]
  resources: ["daemonsets/status"]
  verbs: ["get"]
