{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cachemachine.serviceAccountName" . }}
  labels:
{{ include "cachemachine.labels" . | indent 4 }}
{{- end -}}
