apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cachemachine.serviceAccountName" . }}
  labels:
{{ include "cachemachine.labels" . | indent 4 }}
{{- if .Values.pull_secret }}
imagePullSecrets:
- name: {{ .Values.pull_secret }}
{{- end }}
