{{ if .Values.vault_secrets.enabled }}
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ .Values.docker_secret_name }}
  labels:
    app: {{ template "cachemachine.fullname" . }}
{{ include "cachemachine.labels" . | indent 4 }}
spec:
  path: {{ .Values.vault_secrets.path }}
  type: kubernetes.io/dockerconfigjson
{{ end }}
