# Default values for cadc-tap.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Number of pods to start
replicaCount: 1

# -- Override the base name for resources
nameOverride: ""

# -- Override the full name for resources (includes the release name)
fullnameOverride: ""

image:
    # -- tap-postgres image to use
  repository: "lsstdax/tap-postgres-server"

  # -- Pull policy for the tap image
  pullPolicy: "IfNotPresent"

  # -- Tag of tap image to use
  # @default -- The appVersion of the chart
  tag: ""

# -- Secret names to use for all Docker pulls
imagePullSecrets: []

service:
  # -- Type of service to create
  type: "ClusterIP"

  # -- Port of the service to create and map to the ingress
  port: 80

# Settings for the ingress rules.
ingress:
  # -- Hostname for the ingress
  # @default -- None, must be set
  host: ""

  # -- Gafaelfawr auth query string
  gafaelfawrAuthQuery: "scope=read:tap"

  # -- Additional annotations to use for endpoints that allow anonymous
  # access, such as `/capabilities` and `/availability`
  anonymousAnnotations: {}

  # -- Additional annotations to use for endpoints that are authenticated,
  # such as `/sync`, `/async`, and `/tables`
  authenticatedAnnotations: {}

# -- Resource limits and requests for the cadc-tap-postgres pod
resources: {}

# -- Annotations for the cadc-tap-postgres pod
podAnnotations: {}

# -- Node selector rules for the cadc-tap-postgres pod
nodeSelector: {}

# -- Tolerations for the cadc-tap-postgres pod
tolerations: []

# -- Affinity rules for the cadc-tap-postgres pod
affinity: {}

# -- Path to the Vault secret (`secret/k8s_operator/<host>/tap`, for example)
# @default -- None, must be set
vaultSecretsPath: ""

config:
  # -- Name of GCS bucket in which to store results
  # @default -- None, must be set
  gcsBucket: ""

  # -- Base URL for results stored in GCS bucket
  # @default -- None, must be set
  gcsBucketUrl: ""

db:
  image:
    # -- Database image to use
    repository: "lsstdax/tap-postgres-db"

    # -- Pull policy for the database image
    pullPolicy: "IfNotPresent"

    # -- Tag of database image to use
    # @default -- The appVersion of the chart
    tag: ""

  # -- Resource limits and requests for the database pod
  resources: {}

  # -- Annotations for the databse pod
  podAnnotations: {}

  # -- Node selection rules for the database pod
  nodeSelector: {}

  # -- Tolerations for the database pod
  tolerations: []

  # -- Affinity rules for the database pod
  affinity: {}

uws:
  image:
    # -- UWS database image to use
    repository: "lsstdax/tap-postgres-uws"

    # -- Pull policy for the UWS database image
    pullPolicy: "IfNotPresent"

    # -- Tag of UWS database image to use
    # @default -- The appVersion of the chart
    tag: ""

  # -- Resource limits and requests for the UWS database pod
  resources: {}

  # -- Annotations for the UWS databse pod
  podAnnotations: {}

  # -- Node selection rules for the UWS database pod
  nodeSelector: {}

  # -- Tolerations for the UWS database pod
  tolerations: []

  # -- Affinity rules for the UWS database pod
  affinity: {}
