apiVersion: "kafka.strimzi.io/{{ .Values.strimziAPIVersion }}"
kind: KafkaTopic
metadata:
  name: "{{ .Values.replayTopicName }}"
  labels:
    strimzi.io/cluster: "{{ .Values.clusterName }}"
spec:
  partitions: 8
  replicas: 2
  config:
    cleanup.policy: "delete"
    retention.ms: "{{ .Values.maxMillisecondsRetained }}" # 7 days
    retention.bytes: "{{ .Values.maxBytesRetained }}"
