apiVersion: "kafka.strimzi.io/{{ .Values.strimziAPIVersion }}"
kind: KafkaTopic
metadata:
  name: {{ template "alertStreamSimulator.staticTopicName" . }}
  labels:
    strimzi.io/cluster: "{{ .Values.clusterName }}"
spec:
  partitions: 8
  replicas: 2
  config:
    message.max.bytes: "10000000"  # 10MB
    retention.ms: "-1" # infinite
    retention.bytes: "-1"
---
apiVersion: "kafka.strimzi.io/{{ .Values.strimziAPIVersion }}"
kind: KafkaTopic
metadata:
  name: "{{ .Values.replayTopicName }}"
  labels:
    strimzi.io/cluster: "{{ .Values.clusterName }}"
spec:
  partitions: 8
  replicas: 2
  config:
    cleanup.policy: "delete"
    message.max.bytes: "10000000"  # 10MB
    retention.ms: "604800000" # 7 days
    retention.bytes: "-1"
