apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "times-square-ui.fullname" . }}
  labels:
    {{- include "times-square-ui.labels" . | nindent 4 }}
data:
  times-square.config.yaml: |
    siteName: {{ .Values.config.siteName | quote }}
    siteDescription: |
      {{ .Values.config.siteDescription }}
    baseUrl: https://{{ .Values.ingress.host }}{{ .Values.ingress.path }}
    timesSquareApiUrl: https://{{ .Values.ingress.host }}{{ .Values.config.timesSquareApiPath }}
    {{- if .Values.config.semaphoreUrl }}
    semaphoreUrl: https://{{ .Values.ingress.host }}{{ .Values.config.semaphorePath }}
      {{ .Values.config.semaphoreUrl }}
    {{- end}}
