apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "squareone.fullname" . }}
  labels:
    {{- include "squareone.labels" . | nindent 4 }}
data:
  squareone.config.yaml: |
    siteName: {{ .Values.config.siteName | quote }}
    baseUrl: https://{{ .Values.ingress.host | default "example.com" }}
    siteDescription: |
      {{ .Values.config.siteDescription }}
    {{- if .Values.config.semaphoreUrl }}
    semaphoreUrl: |
      {{ .Values.config.semaphoreUrl }}
    {{- end}}
