apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/server-snippet: |
      location @Basic401 {
          add_header 'WWW-Authenticate' 'Basic' always;
          return 401;
      }
  name: {{ template "helpers.fullname" . }}-oauth2-proxy
spec:
  rules:
{{ if .Values.host }}
  - host: {{ .Values.host }}
    http:
{{ else }}
  - http:
{{ end }}
      paths:
      - backend:
          serviceName: {{ template "helpers.fullname" . }}-oauth2-proxy
          servicePort: 4180
        path: /oauth2
