apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "helpers.fullname" . }}-well-known-jwks
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - backend:
          serviceName: {{ template "helpers.fullname" . }}-well-known-jwks
          servicePort: 80
        path: /.well-known/jwks.json
