apiVersion: v1
description: The mobu generates system load by pretending to be a random scientist
home: https://github.com/lsst-sqre/mobu
maintainers:
  - name: cbanek
name: mobu
version: 0.1.8
appVersion: 1.0.7
