# Default values for mobu.

# -- Base URL used to find other services in the environment such as Nublado
# and TAP
# @default -- None, must be set
environmentUrl: ""

# -- Path to the Vault secret containing the Slack alert hook
# @default -- None, must be set
vaultSecretsPath: ""

# -- Override the base name for resources
nameOverride: ""

# -- Override the full name for resources (includes the release name)
fullnameOverride: ""

image:
  # -- mobu image to use
  repository: lsstsqre/mobu

  # -- Pull policy for the mobu image
  pullPolicy: IfNotPresent

  # -- Tag of mobu image to use
  # @default -- The appVersion of the chart
  tag: ""

# -- Secret names to use for all Docker pulls
imagePullSecrets: []

ingress:
  # -- Whether to create an ingress
  enabled: true

  # Additional annotations to add to the ingress
  annotations:
    nginx.ingress.kubernetes.io/auth-method: "GET"
    nginx.ingress.kubernetes.io/auth-url: "http://gafaelfawr.gafaelfawr.svc.cluster.local:8080/auth?scope=exec:admin"

  # -- Hostname for the ingress
  # @default -- None, must be set if the ingress is enabled
  host: ""

  # -- Configures TLS for the ingress if needed. If multiple ingresses share
  # the same hostname, only one of them needs a TLS configuration.
  tls: []

# -- Resource limits and requests for the mobu frontend pod
resources: {}

# -- Annotations for the mobu frontend pod
podAnnotations: {}

# -- Node selector rules for the mobu frontend pod
nodeSelector: {}

# -- Tolerations for the mobu frontend pod
tolerations: []

# -- Affinity rules for the mobu frontend pod
affinity: {}
