---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plot-navigator
  {{- with .Values.ingress.annotations }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  - host: {{ required "hostname not set" .Values.hostname | quote }}
    http:
      paths:
      - path: {{ .Values.basePath }}
        pathType: ImplementationSpecific
        backend:
          service:
            name: plot-navigator
            port:
              number: 80
