{{- if .Values.influxdb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kafka-connect-manager.name" . }}
  labels:
    helm.sh/chart: {{ include "kafka-connect-manager.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "kafka-connect-manager.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "kafka-connect-manager.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name:  {{ include "kafka-connect-manager.name" . }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy:  {{ .Values.image.pullPolicy }}
        command:
        - connect_manager
        - create
        - influxdb-sink
        {{- if .Values.influxdb.name | quote }}
        - --name
        - {{ .Values.influxdb.name | quote }}
        {{- end }}
        - --influxdb_url
        - {{ .Values.influxdb.influxdbUrl | quote }}
        - --database
        - {{ .Values.influxdb.database | quote }}
        - --tasks
        - {{ .Values.influxdb.tasks | quote }}
        - --filter
        - {{ .Values.influxdb.filter | quote }}
        {{- range .Values.influxdb.blacklist }}
        - --blacklist
        - {{ . | quote }}
        {{- end }}
        - --error-policy
        - {{ .Values.influxdb.errorPolicy | quote }}
        {{- if .Values.influxdb.autoUpdate }}
        - --auto-update
        - --check-interval
        - {{ .Values.influxdb.checkInterval | quote }}
        {{- end }}
        {{- if .Values.influxdb.timestamp }}
        - --timestamp
        - "{{ .Values.influxdb.timestamp  | quote }}"
        {{- end }}
        env:
          - name: BROKER
            value: {{ .Values.env.broker | quote }}
          - name: KAFKA_CONNECT
            value: {{ .Values.env.kafkaConnect | quote }}
          - name: INFLUXDB_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.influxdb.existingSecret }}
                key: influxdb-user
          - name: INFLUXDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.influxdb.existingSecret }}
                key: influxdb-password
{{- end }}
