apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "times-square.fullname" . }}
  labels:
    {{- include "times-square.labels" . | nindent 4 }}
data:
  SAFIR_NAME: {{ .Values.config.name | quote }}
  SAFIR_PROFILE: {{ .Values.config.profile | quote }}
  SAFIR_LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  TS_ENVIRONMENT_URL: {{ .Values.config.environmentUrl | quote }}
  TS_PATH_PREFIX: {{ .Values.ingress.path }}
  TS_REDIS_URL: "redis://{{ include "times-square.fullname" . }}-redis-master.{{ .Release.Namespace }}:{{ .Values.redis.master.service.ports.redis }}/0"
