kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "nublado.fullname" . }}-hub
rules:
- apiGroups: [""]
  resources: ["pods","events","services","configmaps","serviceaccounts","secrets"]
  verbs: ["get", "list", "create", "watch", "delete"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]
- apiGroups: ["argoproj.io"]
  resources: ["workflows", "workflows/finalizers"]
  verbs: ["get", "list", "create", "watch", "delete", "update", "patch"]
- apiGroups: ["argoproj.io"]
  resources: ["workflowtemplates", "workflowtemplates/finalizers"]
  verbs: ["get", "list", "watch"]
