{{ if not .Values.vault_secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nublado.fullname" . }}-hub
type: Opaque
stringData:
  allowed_groups: '{{.Values.allowed_groups}}'
  forbidden_groups: '{{.Values.forbidden_groups}}'
  session_db_url: '{{.Values.session_db_url}}'
  {{- if .Values.hub.crypto_key }}
  jupyterhub_crypto_key: '{{.Values.hub.crypto_key}}'
  {{- else }}
  jupyterhub_crypto_key: '{{ randAlphaNum 32 | b64enc }}'
  {{- end }}

  {{- if .Values.hub.proxy_auth_token }}
  configproxy_auth_token: '{{.Values.hub.proxy_auth_token}}'
  {{- else }}
  configproxy_auth_token: '{{randAlphaNum 32 | b64enc }}:{{randAlphaNum 32 | b64enc }}'
  {{- end }}
{{ end }}
