{{- if .Values.kafka.externalListener.bootstrap.host }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.cluster.name }}-external-tls

spec:
  secretName: {{ .Values.cluster.name }}-external-tls

  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer

  subject:
    organizations:
      - {{ .Values.tls.subject.organization }}

  dnsNames:
    - {{ .Values.kafka.externalListener.bootstrap.host }}
    {{- range _, $broker := .Values.kafka.externalListener.brokers }}
    - {{ $broker.host }}
    {{- end }}
{{- end }}
